### PR TITLE
Fixed mailer-id to be common type, so it works with C# client generation

### PR DESCRIPTION
**Pull request by kendallb**
Can't really use oneOf with properties that have the same name, but are not the same type if we expect client generation to work with strongly typed languages like C#.

### CODE REVIEW

**Comment by kendallb** [comment]
Also changed package_id to be nullable since it can actually be null in the real responses:

``` json
      "packages": [
        {
          "package_id": null,
          "package_code": "fedex_envelope_onerate",
          "name": "FedEx One Rate® Envelope",
          "description": "FedEx® Envelope"
        },
```

**Comment by JamesMessinger** [comment]
Hey @kendallb - just wanted to let you know that I'm not ignoring you.  Just crazy busy right now. 😰  I'll take a look at this PR as soon as I can.

**Comment by kendallb** [comment]
No worries. As I work through using the API I expect to find more of these so we can wait until I am done and do it all at once.

**Comment by vesrah** [comment]
Thank you, I was able to generate C# with openapi-generator by using your branch.

**Comment by kendallb** [comment]
You may want to just use my pre-generated library?

https://github.com/kendallb/ShipEngineApi

https://www.nuget.org/packages/ShipEngineApi/

It's what we use in production and I maintain it as we run into issues. Some stuff is fixed in there that I don't recall if we found a solution in the schema for.

**Comment by kendallb** [comment]
I am curious though, I use my own modified version of NSwag to generate it, as there are some things that do not generate correctly in C# with the way the API is set up (oneOf stuff) and I hacked NSwag to fix it, but they have not accepted my changes upstream yet. So curious how your generated bindings work for stuff that needs oneOf:

https://github.com/kendallb/NSwag

https://github.com/RicoSuter/NSwag/issues/2991

**Comment by vesrah** [comment]
It seems I spoke too soon, the generation also didn't work properly for me.  Unfortunately, your package doesn't have the models, which the project I am working on is already reliant upon.

**Comment by kendallb** [comment]
Which models in particular? I have not worked with an updated schema for a while, so we could integrate the latest schema and generate a new library to see if that includes what you need?

**Comment by vesrah** [comment]
The roundabout explanation of where I am is that we've used the 1.2.30 offical NuGet package for years, which is tied to RestSharp 105.1.0, but we now have other new packages with dependencies on RestSharp 106.3.1.  A binding redirect can't be used since there is no publicKeyToken for RestSharp 105.1.0.

It seems that ShipEngine has made a number of changes in the last three years, so I think we're going to end up using your package and updating our integration.

**Comment by kendallb** [comment]
Sounds good, let me know if there are any bits missing or not working I can certainly fix them for you.

**Pull request closed without merging**
